package api.payload;

public class TweetRequest {
	
	/*
	 * Request payload:
	 * { "title": "aa", "body": "ab", "userId": 3 }
	 */
	
	String title;
	String body;
	//int userId;
	double userId;
	
	/*
	 * Response payload:
	 * { "title": "aa", "body": "ab", "userId": 3, "id": 101 }
	 * Id is part of response payload along with title, body & userId.
	 * This is being generated by API. If we are representing same pojo/business 
	 * object for request and response, then we should make the below field as 
	 * either transient  --> is used to say the field is not part of 
	 * serialization (java to json) process
	 * or annotate with @Expose(serialize = false, deserialize = true)
	 * 
	 * Syntax: public transient String id;
	 * check this video implementation https://www.youtube.com/watch?v=UJMPwQoinas
	 * and add assertions with annotation method of declaring id value.
	 */	
	
	
//private transient String id;
	
	
	public TweetRequest(String title, String body, double id) {
		super();
		this.title = title;
		this.body = body;
		this.userId = id;
	}
	public TweetRequest() {
		// TODO Auto-generated constructor stub
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getBody() {
		return body;
	}
	public void setBody(String body) {
		this.body = body;
	}
	
	public double getUserId() {
		return userId;
	}
	public void setUserId(double userId) {
		this.userId = userId;
	}
	
	
	/*
	 * public String getId() { return id; } public void setId(String id) { this.id =
	 * id; }
	 */
	@Override
	public String toString() {
		return "TweetRequest [title=" + title + ", body=" + body + ", id=" + userId + "]";
	}

}
